### Joining both datasets

In [2]:
import pandas as pd

df_negatives = pd.read_csv("bc_weather_negatives.csv")
df_positives = pd.read_csv("bc_weather_fires.csv")

In [3]:
final_ml_dataset = pd.concat([df_negatives, df_positives], ignore_index=True)

In [4]:
final_ml_dataset = final_ml_dataset.drop(columns=["SIZE_HA"])

In [5]:
final_ml_dataset = final_ml_dataset.sample(frac = 1).reset_index(drop = True)

In [6]:
final_ml_dataset = final_ml_dataset.sample(frac=1).reset_index(drop=True)

In [7]:
final_ml_dataset

,DAY,LATITUDE,LONGITUDE,MONTH,YEAR,label,total_precipitation_sum,temperature_c,dewpoint_c
0,21,56.745300,-125.238200,7,2024,1,1.161098e-05,21.339619,11.349463
1,19,57.909178,-120.272857,10,2024,0,2.796401e-03,-1.011031,-3.593176
2,9,48.863600,-123.721500,5,2019,1,8.583069e-07,17.969802,6.424316
3,19,50.666080,-116.140093,10,2024,0,1.057533e-02,0.992875,-0.855546
4,30,51.075600,-118.666400,6,2015,1,8.839691e-03,16.777808,12.932867
...,...,...,...,...,...,...,...,...,...
45233,19,52.062190,-122.433626,10,2024,0,1.485412e-03,3.932735,1.422937
45234,1,50.448600,-120.362800,7,2021,1,3.292561e-04,26.357472,11.060046
45235,19,53.730252,-116.699528,10,2024,0,3.454541e-03,3.815629,-1.018795
45236,19,59.512150,-136.428909,10,2024,0,6.591384e-03,-11.011194,-14.298417
45237,19,53.469112,-124.879137,10,2024,0,2.690454e-03,4.535681,2.419031

In [8]:
final_ml_dataset.to_csv("bc_fire_ml_dataset.csv", index = False)

### Combining 3_day_before Datasets

In [1]:
import pandas as pd

df_negatives = pd.read_csv("../same-day/datasets/post-processed/2010-2024/bc_weather_negatives.csv")
df_positives = pd.read_csv("../three-days-before/datasets/post-processed/2010-2024/3daybefore_bc_weather_fires.csv")

In [2]:
final_ml_dataset = pd.concat([df_negatives, df_positives], ignore_index=True)

In [3]:
final_ml_dataset = final_ml_dataset.drop(columns=["SIZE_HA"])

In [4]:
final_ml_dataset = final_ml_dataset.sample(frac = 1).reset_index(drop = True)

In [5]:
final_ml_dataset

,DAY,LATITUDE,LONGITUDE,MONTH,YEAR,label,total_precipitation_sum,temperature_c,dewpoint_c
0,19,57.950180,-117.100408,10,2024,0,0.003290,0.293087,-1.666581
1,19,59.043663,-117.682265,10,2024,0,0.005065,-2.473596,-5.875077
2,19,54.937733,-118.097636,10,2024,0,0.004812,4.252152,1.490401
3,7,50.888400,-122.855900,8,2013,1,0.000010,19.236214,8.458111
4,19,56.107955,-131.974956,10,2024,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
45233,19,55.526793,-131.652230,10,2024,0,0.012457,6.106889,5.589278
45234,19,54.675373,-124.574808,10,2024,0,0.010447,3.391231,3.067468
45235,12,49.261300,-116.103500,8,2015,1,0.000000,22.924378,4.295311
45236,17,51.848000,-121.204200,7,2015,1,0.000003,15.090720,4.892018
45237,19,56.899803,-135.097769,10,2024,0,0.010552,2.636592,0.269779

In [6]:
final_ml_dataset.to_csv("3daysbefore_bc_fire_ml_dataset.csv", index = False)